// Ürünler, bölgeler ve SSS içerikleri. Bilgi değişince yalnızca bu dosyayı ve site.config.json'u düzenleyin.
// Kural: doğrulanmamış bilgi (fiyat, saat, depozito, ödeme yöntemi) yazılmaz.

export const URUNLER = [
  {
    id: "damacana",
    slug: "19-litre-damacana-su",
    ad: "19 L Damacana Su",
    kisaAd: "19 L damacana",
    birim: "adet",
    foto: "mayadag-19l",
    fotoAlt: "Kalfaköy Mayadağ Doğal Kaynak Suyu 19 L damacana, bayimizdeki stoktan",
    ozet: "Çatalca Kalfaköy kaynaklı Mayadağ doğal kaynak suyu, 19 litrelik damacanada. En kısa sürede kapınızda.",
    baslik: "Mayadağ Su Siparişi | 19 L Damacana Su, Büyükçekmece",
    aciklama: "Mayadağ su siparişi: Çatalca Kalfaköy kaynaklı doğal kaynak suyu, 19 L damacanada. Celaliye, Kamiloba, Kumburgaz ve Büyükçekmece'ye kapıya teslim.",
    h1: "Mayadağ 19 L Damacana Su",
    h1Vurgu: "Mayadağ, en kısa sürede kapınızda.",
    giris: "Evin ve iş yerinin temel suyu: Çatalca Kalfaköy'deki kaynaktan gelen Mayadağ Doğal Kaynak Suyu, 19 litrelik damacanada. Siparişinizi verin, en kısa sürede kapınıza getirelim.",
    maddeler: [
      ["damla", "Kalfaköy kaynağı", "Mayadağ Doğal Kaynak Suyu, Çatalca Kalfaköy'den; içme, çay-kahve ve yemek için."],
      ["kalkan", "Hijyenik dolum", "Damacanalar dolum tesisinde el değmeden doldurulur ve kapaklanır."],
      ["kamyon", "Hızlı teslimat", "Büyükçekmece genelinde siparişler en kısa sürede teslim edilir."],
      ["tekrar", "Düzenli teslimat", "Haftalık ya da iki haftada bir; her seferinde yeniden aramanıza gerek yok."],
    ],
    bolumler: [
      ["Damacanayı nasıl saklamalı?", "Damacanayı doğrudan güneş almayan, serin ve kokusuz bir yerde saklayın. Deterjan, yakıt gibi kokulu ürünlerin yanında bekletmeyin. Açılmış damacanayı kısa sürede tüketmek, suyun tazeliğini korur."],
      ["Pompa ve sebil temizliği", "Damacana değişiminde pompanın ağzını ve hortumunu temiz suyla durulayın. Sebil kullanıyorsanız üreticinin önerdiği aralıklarla hazneyi temizletin. Temiz ekipman, suyun tadını doğrudan etkiler."],
    ],
    hesaplayici: true,
    sss: [
      ["Bir damacana kaç günde biter?", "Kişi başı günde yaklaşık 2 litre içme ve yemek suyu hesabıyla: 2 kişilik bir evde yaklaşık 4–5 gün, 4 kişilik bir evde 2–3 gün yeter. Sayfadaki hesaplayıcı ile kendi evinize göre bakabilirsiniz."],
      ["Ne kadar sürede teslim ediyorsunuz?", "Büyükçekmece, Celaliye, Kamiloba ve Kumburgaz'dan gelen siparişleri en kısa sürede kapınıza getiriyoruz. Belirli bir saat istiyorsanız siparişte belirtin."],
      ["Damacana depozitolu mu?", "Evet. 19 L polikarbonat damacanalar depozitoludur. Güncel depozito bedeli ve boş damacana değişimi için bizi arayın ya da WhatsApp'tan yazın."],
      ["Her hafta düzenli getirebilir misiniz?", "Evet. Sipariş formunda \"Düzenli teslimat istiyorum\" seçeneğini işaretleyin, teslim gününü birlikte planlayalım."],
    ],
  },
  {
    id: "pompa",
    slug: "damacana-su-pompasi",
    ad: "Damacana Su Pompası",
    kisaAd: "Pompa",
    birim: "adet",
    varyantlar: ["Manuel pompa", "Şarjlı pompa"],
    foto: "desa-pompa",
    fotoAlt: "Manuel damacana pompası, ambalajında, bayimizde",
    ozet: "Manuel ve şarjlı modeller. Damacanadan bardağa, dökmeden ve israf etmeden.",
    baslik: "Damacana Su Pompası | Manuel ve Şarjlı, Büyükçekmece",
    aciklama: "Büyükçekmece'de damacana su pompası: manuel ve şarjlı modeller. Damacana siparişinizle birlikte en kısa sürede kapınıza getirelim.",
    h1: "Damacana Su Pompası",
    h1Vurgu: "suyunuzla birlikte gelsin.",
    giris: "Damacanayı kaldırmadan, dökmeden su almanın en pratik yolu. Manuel ve şarjlı (otomatik) pompa seçeneklerini damacana siparişinizle birlikte getiriyoruz.",
    maddeler: [
      ["el", "Manuel pompa", "Elektrik gerektirmez; basit, dayanıklı ve kolay temizlenir."],
      ["pil", "Şarjlı pompa", "Tek dokunuşla akış; mutfakta ve ofiste zaman kazandırır."],
      ["damla", "Dökmeden, israfsız", "Damacanayı kaldırıp devirmeye gerek kalmaz, su boşa gitmez."],
      ["kamyon", "Siparişle birlikte", "Damacana siparişinize ekleyin, aynı teslimatta gelsin."],
    ],
    bolumler: [
      ["Pompa nasıl takılır?", "Damacananın kapağındaki etiketi çıkarın, pompanın hortumunu damacana ağzına yerleştirip bastırarak oturtun. Şarjlı modellerde kullanmadan önce cihazı tam şarj edin."],
      ["Pompayı nasıl temiz tutarım?", "Her damacana değişiminde hortumu ve çıkış ağzını temiz suyla durulayın. Pompayı kullanmadığınızda ağzını kapalı ve tozdan uzak tutun."],
    ],
    sss: [
      ["Hangi pompa modelleri var?", "Manuel (basmalı) ve şarjlı (otomatik) modeller sunuyoruz. Güncel modeller için WhatsApp'tan yazmanız yeterli."],
      ["Pompayı damacanayla birlikte getirir misiniz?", "Evet. Sipariş formunda pompayı da ekleyin, aynı teslimatta getirelim."],
    ],
  },
  {
    id: "bardak",
    slug: "bardak-su",
    ad: "Bardak Su",
    kisaAd: "Bardak su",
    birim: "koli",
    foto: "baharlife-bardak-su",
    fotoAlt: "Bardak su kolileri, bayimizdeki stok",
    ozet: "200 ml bardak su, koli halinde. Toplantı, misafir, kafe ve etkinlikler için.",
    baslik: "Bardak Su Siparişi | Ofis, Kafe ve Etkinlik",
    aciklama: "Bardak su siparişi, koli halinde. Ofis, kafe, toplantı ve etkinlikler için Büyükçekmece'de hızlı kapıya teslimat.",
    h1: "Bardak Su Siparişi",
    h1Vurgu: "ofis, kafe ve etkinlikler için.",
    giris: "Toplantı odası, bekleme salonu, kafe ya da düğün-etkinlik… Bardak su hijyenik, tek kullanımlık ve dağıtması kolay. Koli halinde, istediğiniz miktarda getiriyoruz.",
    maddeler: [
      ["kalkan", "Tek kullanımlık, hijyenik", "Kapalı ambalaj; bardak yıkama derdi yok."],
      ["bina", "İşletmeler için", "Ofis, kafe, market ve bekleme salonları için düzenli teslimat."],
      ["takvim", "Etkinliğe göre", "Düğün, toplantı ve organizasyonlar için toplu sipariş."],
      ["kamyon", "Hızlı teslimat", "Büyükçekmece genelinde en kısa sürede teslim."],
    ],
    bolumler: [
      ["Etkinlik için ne kadar sipariş vermeliyim?", "Kabaca kişi başı 2–3 bardak hesaplayın; yaz aylarında ve açık hava etkinliklerinde bu sayı artar. Bir koli genellikle 60 bardaktır; örneğin 100 kişilik bir etkinlik için 4–5 koli çoğu zaman yeterli olur. Kişi sayısını ve süreyi yazarsanız miktarı birlikte netleştirelim."],
    ],
    sss: [
      ["Bir kolide kaç bardak var?", "Kolilerde genellikle 200 ml'lik 60 bardak bulunur; ürüne göre değişebilir."],
      ["İşyerimize düzenli getirebilir misiniz?", "Evet. Haftalık ya da ihtiyaç duyduğunuz sıklıkta düzenli teslimat planlayabiliriz."],
    ],
  },
  {
    id: "pet",
    slug: "pet-su",
    ad: "0,5 L Pet Su",
    kisaAd: "0,5 L pet su",
    birim: "paket",
    foto: "seda-pet-su",
    fotoAlt: "0,5 litre pet su şişeleri, bayimizdeki stok",
    ozet: "0,5 L (05'lik) pet su, paket halinde. Çanta, ofis, spor ve yolculuk için.",
    baslik: "0,5 L Pet Su Siparişi (05'lik) | Büyükçekmece",
    aciklama: "0,5 litre (05'lik) pet su siparişi, paket halinde. Ofis, spor salonu ve etkinlikler için Büyükçekmece'de hızlı kapıya teslimat.",
    h1: "0,5 L Pet Su",
    h1Vurgu: "paket halinde, kapınızda.",
    giris: "Çantaya, arabaya, spor salonuna… 0,5 litrelik (05'lik) PET şişe su her yerde yanınızda. Paket halinde sipariş verin, taşıma derdi olmadan kapınıza gelsin.",
    maddeler: [
      ["canta", "Taşıması kolay", "Çantaya ve arabaya sığar; gün boyu yanınızda."],
      ["bina", "Ofis ve mağaza", "Misafir ve müşteri ikramı için pratik."],
      ["takvim", "Etkinlik ve spor", "Maç, antrenman, piknik ve organizasyonlar için toplu sipariş."],
      ["kamyon", "Hızlı teslimat", "Paketleri kapınıza kadar biz taşırız."],
    ],
    bolumler: [
      ["Pet şişe su nasıl saklanır?", "Pet şişeleri güneş almayan, serin bir yerde saklayın; arabada uzun süre sıcakta bırakmayın. Açılan şişeyi aynı gün içinde tüketin."],
    ],
    sss: [
      ["Bir pakette kaç şişe var?", "Paket içeriği değişebilir. Güncel bilgi için WhatsApp'tan yazmanız yeterli."],
      ["1,5 litre pet su da var mı?", "Evet. 1,5 litre pet su ayrı bir ürün olarak var; sipariş formunda ayrıca seçebilirsiniz."],
      ["Damacanayla aynı siparişte gelir mi?", "Evet. Sipariş formunda damacana ve pet suyu birlikte seçin, tek teslimatta getirelim."],
    ],
  },
  {
    id: "pet15",
    slug: "1-5-litre-pet-su",
    ad: "1,5 L Pet Su",
    kisaAd: "1,5 L pet su",
    birim: "paket",
    foto: "pet-15-foto",
    fotoAlt: "Mavi kapaklı pet şişe su",
    ozet: "1,5 litre pet şişe su, paket halinde. Ev, sofra ve ofis masası için ideal boy.",
    baslik: "1,5 Litre Pet Su Siparişi | Büyükçekmece",
    aciklama: "1,5 litre pet şişe su siparişi, paket halinde. Ev, sofra, ofis ve işletmeler için Büyükçekmece'de hızlı kapıya teslimat. WhatsApp'tan sipariş verin.",
    h1: "1,5 L Pet Su",
    h1Vurgu: "sofranıza, paket halinde.",
    giris: "Evin sofrası, ofis masası ya da dükkân tezgâhı için 1,5 litre pet şişe su. Paket halinde sipariş verin, taşımadan kapınıza gelsin.",
    maddeler: [
      ["damla", "Sofra boyu", "Yemek masası ve ev kullanımı için ideal hacim."],
      ["bina", "Ofis ve dükkân", "Masa başı ve tezgâh için pratik."],
      ["tekrar", "Düzenli teslimat", "Damacana siparişinizle birlikte haftalık getirebiliriz."],
      ["kamyon", "Hızlı teslimat", "Paketleri kapınıza kadar biz taşırız."],
    ],
    bolumler: [
      ["Pet şişe su nasıl saklanır?", "Pet şişeleri güneş almayan, serin bir yerde saklayın; arabada uzun süre sıcakta bırakmayın. Açılan şişeyi kısa sürede tüketin."],
    ],
    sss: [
      ["Bir pakette kaç şişe var?", "Paket içeriği ürüne göre değişebilir. Güncel bilgi için WhatsApp'tan yazmanız yeterli."],
      ["Damacanayla aynı siparişte gelir mi?", "Evet. Sipariş formunda damacana ve 1,5 L pet suyu birlikte seçin, tek teslimatta getirelim."],
    ],
  },
  {
    id: "tup",
    slug: "tup-gaz",
    ad: "Tüp Gaz",
    kisaAd: "Tüp gaz",
    birim: "adet",
    foto: "tup-gaz-gercek",
    fotoAlt: "12 kg mutfak tüpü",
    ozet: "Milangaz, Likitgaz ve Ergaz tüp gaz: mutfak, ticari ve sanayi tüpü; forklift tüpü ve Palmiye ısıtıcı.",
    hizmetTuru: "Tüp gaz teslimatı",
    tupRehber: true,
    baslik: "Tüp Gaz Siparişi Büyükçekmece | Milangaz, Likitgaz, Ergaz",
    aciklama: "Büyükçekmece tüp gaz siparişi: Milangaz, Likitgaz ve Ergaz tüp Celaliye, Kamiloba ve Kumburgaz'a kapıya teslim. Su siparişinizle birlikte tek teslimatta.",
    h1: "Tüp Gaz Siparişi",
    h1Vurgu: "üç marka, kapınıza kadar.",
    giris: "Tüpünüz bittiğinde tek telefon yeter. Milangaz, Likitgaz ve Ergaz mutfak tüpünü kapınıza getiriyoruz; damacana siparişinizle aynı teslimatta da gelebilir. İşletmeler için Milangaz LiftMax forklift tüpü ve Palmiye açık hava ısıtıcısı da bizde.",
    maddeler: [
      ["kamyon", "Kapıya teslim", "Ağır tüpü taşımakla uğraşmayın; kapınıza kadar getiriyoruz."],
      ["tekrar", "Suyla birlikte", "Damacana ve tüp gazı tek siparişte, aynı teslimatta alın."],
      ["bina", "LiftMax forklift tüpü", "Depo ve fabrikalar için Milangaz LiftMax: hafif, iç mekân kullanımına uygun."],
      ["alev", "Palmiye ısıtıcı", "Kafe, restoran ve bahçeler için Milangaz Palmiye açık hava ısıtıcısı."],
    ],
    adimlar: [
      "Ocak ve cihaz düğmelerini kapatın, tüpün vanasını kapatın.",
      "Regülatörü boş tüpten çıkarın; contanın yerinde ve sağlam olduğunu kontrol edin.",
      "Dolu tüpün kapağını açın, regülatörü dik tutarak yerine oturtun ve kilitleyin.",
      "Vanayı açıp bağlantı noktalarına sabunlu su sürün. Kabarcık varsa vanayı kapatın ve tekrar takın.",
      "Kabarcık yoksa ocağı yakabilirsiniz. Emin olamazsanız teslimatta bize sorun.",
    ],
    bolumler: [
      ["Tüp gazı güvenle kullanmak için", "Tüpü her zaman dik ve havadar bir yerde tutun; ısı kaynaklarından ve doğrudan güneşten uzak bulundurun. Hortum ve regülatör bağlantılarını düzenli kontrol edin, eskiyen hortumu değiştirin. Bağlantı noktalarında kaçaktan şüpheleniyorsanız sabunlu suyla kontrol edin; kabarcık oluşuyorsa tüpü kullanmayın."],
      ["Gaz kokusu alırsanız", "Tüpün vanasını hemen kapatın ve pencereleri açın. Elektrik düğmelerine dokunmayın, çakmak ya da kibrit yakmayın. Ortamı terk edip 112 Acil Çağrı Merkezi'ni arayın."],
    ],
    sss: [
      ["Hangi marka tüp getiriyorsunuz?", "Milangaz, Likitgaz ve Ergaz. Sipariş formunda markayı seçebilir ya da \"fark etmez\" diyebilirsiniz. İşletmeler için Milangaz LiftMax forklift tüpü ve Palmiye açık hava ısıtıcısı da sağlıyoruz."],
      ["Tüp ve su aynı siparişte gelir mi?", "Evet. Sipariş formunda tüp gazı ve damacanayı birlikte seçin, aynı teslimatta getirelim."],
      ["Evde boş tüpüm yok, ilk kez alacağım. Ne yapmalıyım?", "İlk alımda tüpün kendisi için ayrıca bir bedel söz konusu olabilir. Güncel bilgi için arayın ya da WhatsApp'tan yazın."],
      ["12 kg tombul ve uzun tüp arasındaki fark nedir?", "İkisi de 12 kg LPG alır; tombul tüp 36 cm, uzun tüp 30 cm çapındadır. Dar dolap ve Palmiye tipi ısıtıcılar için genelde uzun tüp tercih edilir."],
    ],
  },
];

// Tüp çeşitleri; ölçüler Milangaz resmî sitesinden (kaynak: milangaz.com.tr ürün sayfaları, Eylül 2026). Stok durumu bayiden teyit edilmeli.
export const TUP_REHBER = [
  ["12 kg mutfak tüpü", "Mutfak, şofben ve ev kullanımı. Tombul (Ø36 cm) ve uzun (Ø30 cm) iki tipi var.", "/hizmetlerimiz/tup-gaz/"],
  ["2 kg piknik tüpü + kamp ocağı", "Piknik ve kamp için; Orgaz kamp ocağıyla birlikte.", "/hizmetlerimiz/kamp-ocagi-piknik-tupu/"],
  ["LPG dedantörü (regülatör)", "Tüple ocak arasındaki basınç ayarlayıcı; Orgaz alçak basınç dedantör.", "/hizmetlerimiz/lpg-dedantoru/"],
  ["24 kg ticari tüp", "Lokanta, fırın, otel gibi yoğun kullanılan işletmeler.", "/hizmetlerimiz/ticari-sanayi-tupu/"],
  ["45 kg sanayi tüpü", "Yüksek tüketimli işletme ve atölyeler; propan ve karışım seçenekleri.", "/hizmetlerimiz/ticari-sanayi-tupu/"],
  ["LiftMax forklift tüpü", "Forkliftler için; 15 kg LPG, dolu hâli 23,5 kg.", "/hizmetlerimiz/forklift-tupu/"],
  ["İzoMax tüp (Milangaz)", "Pürmüz ve şaluma gibi izolasyon uygulamaları için 12 kg tüp.", "/hizmetlerimiz/ticari-sanayi-tupu/"],
  ["ProMaster tüp (Milangaz)", "24 kg; dar alanlarda yüksek performans gereken işletmeler için.", "/hizmetlerimiz/ticari-sanayi-tupu/"],
  ["Palmiye ısıtıcı", "Kafe, restoran ve bahçeler için açık hava ısıtıcısı; 12 kg uzun tüple çalışır.", "/hizmetlerimiz/palmiye-isitici/"],
];

// Tüp alt sayfaları: ürün ızgarasında görünmez, tüp sayfasından bağlanır; sipariş formunda "Tüp gaz" satırı ön seçili gelir.
export const TUP_EK = [
  {
    id: "forklift",
    formUrun: "ozeltup",
    varyant: "LiftMax forklift tüpü",
    hizmetTuru: "Forklift tüpü teslimatı",
    slug: "forklift-tupu",
    ad: "Forklift Tüpü",
    kisaAd: "Forklift tüpü",
    foto: "tup-forklift-gercek",
    fotoAlt: "Milangaz LiftMax forklift tüpü ve forklift, depoda",
    ozet: "Milangaz LiftMax forklift tüpü; depo ve fabrikalara düzenli teslimat.",
    baslik: "Forklift Tüpü Büyükçekmece | Milangaz LiftMax",
    aciklama: "Büyükçekmece'de forklift tüpü: Milangaz LiftMax, 15 kg LPG. Depo, fabrika ve lojistik firmalarına düzenli teslimat. Hemen arayın.",
    h1: "Forklift Tüpü",
    h1Vurgu: "Milangaz LiftMax, işiniz durmasın.",
    giris: "Depo, fabrika ve lojistik alanlarında forkliftleriniz için Milangaz LiftMax tüpü getiriyoruz. Haftalık ihtiyacınızı söyleyin, tüpünüz bitmeden yenisi kapınızda olsun.",
    maddeler: [
      ["alev", "15 kg LPG", "LiftMax 15 kg LPG alır; dolu hâli yaklaşık 23,5 kg'dır."],
      ["bina", "İşletmelere özel", "Depo, fabrika, şantiye ve lojistik firmaları için."],
      ["tekrar", "Düzenli teslimat", "Vardiya düzeninize göre haftalık plan; stok takibini biz yapalım."],
      ["kamyon", "Acil ek sipariş", "Beklenmedik ihtiyaçta en kısa sürede teslim."],
    ],
    bolumler: [
      ["Forklift tüpü nasıl planlanır?", "Kaç forklift çalıştırdığınızı ve bir tüpün size yaklaşık kaç saat yettiğini yazın. Buna göre haftalık kaç tüp gerektiğini birlikte hesaplayıp teslim gününü sabitleyelim; boş tüpleri teslimatta alırız."],
      ["Güvenli kullanım", "Tüpü forklift üzerindeki bağlantısına kilitlemeden kullanmayın. Tüp değişimini motor kapalıyken ve açık ya da iyi havalandırılan bir alanda yapın. Bağlantıda koku veya tıslama fark ederseniz vanayı kapatıp tüpü kullanmayın."],
    ],
    sss: [
      ["Hangi forklift tüpünü getiriyorsunuz?", "Milangaz LiftMax forklift tüpü. Güncel stok ve teslim günleri için arayın ya da WhatsApp'tan yazın."],
      ["Fatura kesiyor musunuz?", "Kurumsal siparişlerde fatura ve ödeme detaylarını sipariş sırasında birlikte netleştiriyoruz."],
      ["Her hafta düzenli getirebilir misiniz?", "Evet. İhtiyacınıza göre sabit gün ve adetle düzenli teslimat planlıyoruz."],
    ],
    waMetin: "Merhaba, forklift tüpü (LiftMax) için bilgi almak istiyorum. Firma / adres / haftalık adet: ",
  },
  {
    id: "palmiye",
    formUrun: "palmiye",
    varyant: "",
    hizmetTuru: "Açık hava ısıtıcısı ve tüp gaz",
    slug: "palmiye-isitici",
    ad: "Palmiye Isıtıcı",
    kisaAd: "Palmiye ısıtıcı",
    foto: "tup-palmiye-gercek",
    fotoAlt: "Milangaz Palmiye açık hava ısıtıcısı, kafe bahçesinde",
    ozet: "Milangaz Palmiye açık hava ısıtıcısı ve 12 kg uzun tüp; kafe, restoran ve bahçeler için.",
    baslik: "Palmiye Isıtıcı ve Tüpü | Büyükçekmece, Milangaz",
    aciklama: "Kafe, restoran, balkon ve bahçeler için Milangaz Palmiye açık hava ısıtıcısı ve 12 kg uzun tüp. Büyükçekmece'de kapıya teslim, tüp yenileme.",
    h1: "Palmiye Isıtıcı",
    h1Vurgu: "açık havada sıcacık oturun.",
    giris: "Kafe, restoran terası, balkon ya da bahçe… Milangaz Palmiye açık hava ısıtıcısı ve onunla kullanılan 12 kg uzun tüpü getiriyoruz. Kış boyunca tüpünüz bitince tek telefonla yenisi gelsin.",
    maddeler: [
      ["alev", "Açık ve yarı açık alanlar", "Teras, bahçe, balkon ve kış bahçeleri için."],
      ["bina", "Kafe ve restoranlar", "Müşterileriniz serin havada da dışarıda oturabilsin."],
      ["tekrar", "Tüp yenileme", "Palmiye ısıtıcılar 12 kg uzun tüple çalışır; tüpünüz bitince getiririz."],
      ["kamyon", "Kapıya teslim", "Isıtıcı ve tüp kapınıza kadar gelir."],
    ],
    bolumler: [
      ["Hangi tüp kullanılır?", "Palmiye tipi ısıtıcılarda 12 kg uzun (30 cm çaplı) tüp kullanılır. Tüp, ısıtıcının alt gövdesindeki bölmeye yerleştirilir."],
      ["Güvenli kullanım", "Palmiye ısıtıcıyı yalnızca açık ya da iyi havalandırılan alanlarda kullanın; kapalı odada kullanmayın. Tentelerden, perdelerden ve yanıcı malzemelerden uzak tutun, devrilmeyecek düz bir zemine koyun. Kullanım bitince tüpün vanasını kapatın."],
    ],
    sss: [
      ["Palmiye ısıtıcı satıyor musunuz?", "Evet, Milangaz Palmiye açık hava ısıtıcısı için bizi arayın; güncel model ve stok bilgisini verelim."],
      ["Isıtıcının tüpünü de getiriyor musunuz?", "Evet. Palmiye ısıtıcılarla kullanılan 12 kg uzun tüpü kapınıza getiriyoruz. Sipariş formunda \"12 kg uzun tüp – ısıtıcı için\" seçeneğini seçin."],
      ["Kapalı alanda kullanılabilir mi?", "Hayır. Açık hava ısıtıcıları yalnızca açık ya da iyi havalandırılan alanlar içindir."],
    ],
    waMetin: "Merhaba, Palmiye ısıtıcı / uzun tüp için bilgi almak istiyorum. Adres: ",
  },
  {
    id: "ticari",
    formUrun: "tup",
    varyant: "24 kg ticari tüp",
    hizmetTuru: "Ticari ve sanayi tüpü teslimatı",
    slug: "ticari-sanayi-tupu",
    ad: "Ticari ve Sanayi Tüpü",
    kisaAd: "Ticari / sanayi tüpü",
    foto: "tup-ticari",
    fotoAlt: "24 kg ve 45 kg tüp illüstrasyonu",
    ozet: "24 kg ticari ve 45 kg sanayi tüpü (Milangaz, Likitgaz, Ergaz); lokanta, fırın, otel ve atölyeler için.",
    baslik: "Ticari ve Sanayi Tüpü | 24 kg, 45 kg Büyükçekmece",
    aciklama: "Lokanta, fırın, otel ve atölyeler için 24 kg ticari ve 45 kg sanayi tüpü; Milangaz, Likitgaz, Ergaz. Büyükçekmece'de işletmelere düzenli teslimat.",
    h1: "Ticari ve Sanayi Tüpü",
    h1Vurgu: "24 kg ve 45 kg, işletmenize.",
    giris: "Mutfağı hiç durmayan lokantalar, fırınlar, oteller ve yüksek tüketimli atölyeler için Milangaz, Likitgaz ve Ergaz 24 kg ticari ve 45 kg sanayi tüpü; izolasyon işleri için Milangaz İzoMax ve ProMaster tüp getiriyoruz.",
    maddeler: [
      ["alev", "24 kg ticari tüp", "Lokanta, fırın, otel, okul ve hastane mutfakları için."],
      ["bina", "45 kg sanayi tüpü", "Yüksek tüketimde daha uzun süre; propan ve karışım seçenekleri."],
      ["tekrar", "Düzenli teslimat", "Tüketiminize göre sabit gün; tüpünüz bitmeden yenisi gelir."],
      ["kamyon", "İşletmenize teslim", "Ağır tüpleri kullanım yerine kadar biz taşırız."],
    ],
    bolumler: [
      ["Hangisi bana uygun?", "Günlük tüketimi yüksek mutfaklarda 24 kg ticari tüp, çok daha yoğun tüketen ya da uzun süre kesintisiz gaz isteyen işletmelerde 45 kg sanayi tüpü tercih edilir. Kullandığınız cihazları ve günlük çalışma saatlerinizi yazın, birlikte karar verelim."],
      ["Güvenli kullanım", "Büyük tüpleri havalandırılan, güneş ve ısı kaynaklarından uzak bir alanda dik tutun. Hortum ve regülatörleri düzenli kontrol ettirin. Gaz kokusu alırsanız vanayı kapatın, alanı havalandırın ve 112'yi arayın."],
    ],
    sss: [
      ["İzoMax ve ProMaster tüp de var mı?", "Evet. Çatı ve izolasyon işlerinde pürmüz ve şaluma için Milangaz İzoMax, dar alanlarda yüksek performans isteyen işletmeler için 24 kg Milangaz ProMaster tüp getiriyoruz."],
      ["24 kg ile 45 kg arasındaki fark nedir?", "24 kg ticari tüp yoğun kullanılan mutfaklar içindir; 45 kg sanayi tüpü daha yüksek debide daha uzun süre gaz sağlar."],
      ["Fatura kesiyor musunuz?", "Kurumsal siparişlerde fatura ve ödeme detaylarını sipariş sırasında birlikte netleştiriyoruz."],
    ],
    waMetin: "Merhaba, işletmemiz için ticari/sanayi tüpü istiyoruz. Firma / adres / tüp tipi: ",
  },
  {
    id: "kamp",
    formUrun: "kamp",
    varyant: "Kamp ocağı + 2 kg piknik tüpü",
    marka: "Orgaz",
    hizmetTuru: "Kamp ocağı ve piknik tüpü satışı",
    slug: "kamp-ocagi-piknik-tupu",
    ad: "Kamp Ocağı ve Piknik Tüpü",
    kisaAd: "Kamp ocağı",
    foto: "kamp-ocagi-tupte",
    fotoAlt: "Kamp ocağı piknik tüpüne takılı, bayimizde",
    ozet: "Orgaz kamp ocağı, kamp lambası ve 2 kg piknik tüpü; piknik, kamp ve bahçe için.",
    baslik: "Kamp Ocağı ve Piknik Tüpü | Büyükçekmece",
    aciklama: "Orgaz kamp ocağı ve 2 kg piknik tüpü: piknik, kamp, bahçe ve balkon için. Büyükçekmece'de kapıya teslim, tüp dolumu ve değişimi.",
    h1: "Kamp Ocağı ve Piknik Tüpü",
    h1Vurgu: "pikniğe hazır.",
    giris: "Piknikte, kampta ya da bahçede çay demlemek için Orgaz kamp ocağı ve 2 kg piknik tüpü; akşamları için Orgaz kamp lambası. Tüp bitince yenisini de kapınıza getiriyoruz.",
    maddeler: [
      ["alev", "Orgaz kamp ocağı", "Piknik tüpünün üstüne takılan, direkt basınçlı kamp ocağı."],
      ["canta", "Kamp lambası", "Piknik tüpüne takılan Orgaz kamp lambası; akşam aydınlatması için."],
      ["tekrar", "Tüp değişimi", "Boş piknik tüpünüzü dolusuyla değiştirelim."],
      ["kamyon", "Kapıya teslim", "Ocak ve tüp kapınıza kadar gelir."],
    ],
    bolumler: [
      ["Kamp ocağı nasıl kullanılır?", "Kamp ocağını piknik tüpünün vanasına dik şekilde oturtup sıkıca takın, düz ve sağlam bir zemine koyun. Vanayı yavaşça açıp ateşleyin; alevi vana ile ayarlayın. Kullanım bitince önce vanayı kapatın, ocak soğuyunca sökün."],
      ["Güvenli kullanım", "Kamp ocağı yalnızca açık alanda kullanılmalıdır; çadır, karavan ya da kapalı odada kullanmayın. Yanıcı malzemelerden ve rüzgârdan korunaklı bir yerde, çocuklardan uzakta kullanın. Conta hasarlıysa ya da gaz kokusu alıyorsanız kullanmayın."],
    ],
    sss: [
      ["Kamp lambası da var mı?", "Evet. Piknik tüpüne takılan Orgaz kamp lambası da satıyoruz; sipariş formundaki \"Kamp Ürünleri\" satırından \"Kamp lambası\"nı seçin."],
      ["Kamp ocağı hangi tüple çalışır?", "Doldurulabilir butan-propan piknik tüpleriyle çalışır. 2 kg piknik tüpüyle birlikte alabilirsiniz."],
      ["Sadece tüp değişimi yapıyor musunuz?", "Evet. Boş piknik tüpünüzü dolusuyla değiştiriyoruz; güncel bilgi için arayın."],
      ["Kapalı alanda kullanılabilir mi?", "Hayır. Ürün ambalajında da belirtildiği gibi kamp ocağı yalnızca dışarıda kullanılmalıdır."],
    ],
    waMetin: "Merhaba, kamp ocağı / piknik tüpü almak istiyorum. Adres: ",
  },
  {
    id: "dedantor",
    formUrun: "dedantor",
    varyant: "",
    marka: "Orgaz",
    hizmetTuru: "LPG dedantörü satışı",
    slug: "lpg-dedantoru",
    ad: "LPG Dedantörü (Regülatör)",
    kisaAd: "Dedantör",
    foto: "orgaz-dedantor",
    fotoAlt: "Orgaz alçak basınç LPG dedantörü MT-300-20, kutusunda, bayimizde",
    ozet: "Orgaz alçak basınç LPG dedantörü (MT-300-20); mutfak tüpü ile ocak arasına.",
    baslik: "LPG Dedantörü (Regülatör) | Büyükçekmece Tüp",
    aciklama: "Orgaz alçak basınç LPG dedantörü MT-300-20: mutfak tüpü ve ocak bağlantısı için regülatör. Büyükçekmece'de tüpünüzle birlikte kapıya teslim.",
    h1: "LPG Dedantörü",
    h1Vurgu: "tüpünüzle birlikte gelsin.",
    giris: "Tüp ile ocağınız arasındaki gaz basıncını ayarlayan dedantör (regülatör). Eskiyen ya da arızalanan dedantörünüzü, tüpünüzle aynı teslimatta yenisiyle değiştirin.",
    maddeler: [
      ["kalkan", "Alçak basınç", "Ev ocakları için alçak basınç LPG dedantörü (Orgaz MT-300-20)."],
      ["tekrar", "Tüpünüzle birlikte", "Dedantörü tüp siparişinize ekleyin, aynı teslimatta gelsin."],
      ["alev", "Güvenli bağlantı", "Sağlam dedantör ve conta, gaz kaçağına karşı ilk önlemdir."],
      ["kamyon", "Kapıya teslim", "Tüp ve dedantör kapınıza kadar gelir."],
    ],
    bolumler: [
      ["Dedantör ne zaman değiştirilmeli?", "Dedantörde çatlak, ezilme ya da gövdede hasar görürseniz; bağlantıda sabunlu su testinde kabarcık çıkıyorsa ya da alev düzensiz yanıyorsa dedantörü ve contasını değiştirin. Emin değilseniz teslimatta bize gösterin."],
      ["Nasıl takılır?", "Tüpün vanası kapalıyken dedantörü tüpün ağzına dik tutarak oturtun ve kilitleyin. Hortumu kelepçeyle sabitleyin. Vanayı açıp bağlantılara sabunlu su sürün; kabarcık yoksa ocağı kullanabilirsiniz."],
    ],
    sss: [
      ["Hangi dedantörü satıyorsunuz?", "Orgaz alçak basınç LPG dedantörü (MT-300-20). Kutusunda 2 yıl garanti belirtilmektedir. Güncel stok için arayın."],
      ["Her tüpe uyar mı?", "Ev tipi mutfak tüplerinde kullanılan standart dedantördür. Tüpünüzün ve ocağınızın tipini yazarsanız uygunluğunu kontrol edelim."],
    ],
    waMetin: "Merhaba, LPG dedantörü almak istiyorum. Adres: ",
  },
];

export const BOLGELER = [
  {
    slug: "celaliye-su-siparisi",
    ad: "Celaliye",
    ek: { e: "ye", de: "de", den: "den" },
    baslik: "Celaliye Su Bayisi | Su Siparişi ve Tüp Gaz",
    aciklama: "Celaliye su ve tüp gaz siparişi: bayimiz Uludere Sokak'ta. Mayadağ damacana, tüp gaz, bardak ve pet su en kısa sürede kapınızda. 0542 787 08 48",
    giris: "Celaliye su bayisi olarak Uludere Sokak'tayız. Mahallenin içinden çıkıp geldiğimiz için Celaliye su siparişleri en hızlı ulaştırdığımız siparişler.",
    paragraflar: [
      "Celaliye'de ev, apartman ya da iş yeri fark etmez: Mayadağ 19 litre damacana, bardak su, 0,5 L ve 1,5 L pet su ve tüp gaz siparişlerinizi en kısa sürede teslim ediyoruz. Bayimize yakınsanız dilerseniz uğrayıp elden de alabilirsiniz.",
      "Apartmanda oturuyorsanız siparişe kat ve asansör bilgisini, site içindeyseniz blok adını yazmanız teslimatı hızlandırır.",
    ],
  },
  {
    slug: "kamiloba-su-siparisi",
    ad: "Kamiloba",
    ek: { e: "ya", de: "da", den: "dan" },
    baslik: "Kamiloba Su Bayisi | Su Siparişi ve Tüp Gaz",
    aciklama: "Kamiloba'ya Mayadağ damacana, tüp gaz, bardak ve pet su teslimatı. Komşu mahalledeyiz, siparişiniz en kısa sürede kapınızda.",
    giris: "Kamiloba'ya en yakın su bayisi Celaliye'deki bayimiz. Damacana su, bardak su, pet su ve tüp gaz siparişlerinizi en kısa sürede kapınıza getiriyoruz.",
    paragraflar: [
      "Kamiloba'daki evler, siteler ve iş yerleri düzenli servis güzergâhımızda. Tek seferlik sipariş verebilir ya da haftalık düzenli teslimat planlayabilirsiniz; suyunuz bitmeden yenisi gelsin.",
      "Site içindeyseniz blok ve daire numarasını, müstakil evdeyseniz tarif için yakındaki bir noktayı sipariş notuna yazmanız yeterli.",
    ],
  },
  {
    slug: "kumburgaz-su-siparisi",
    ad: "Kumburgaz",
    ek: { e: "a", de: "da", den: "dan" },
    telefon: "ikinci",
    baslik: "Kumburgaz Su Bayisi | Su Siparişi, Küme Evler",
    aciklama: "Kumburgaz ve Küme Evler'e Mayadağ damacana, tüp gaz, pet ve bardak su. Yazlık, site ve iş yerlerine hızlı teslimat.",
    giris: "Kumburgaz ve Küme Evler'deki evinize, yazlığınıza ya da sitenize Mayadağ damacana su ve tüp gaz getiriyoruz. Bu bölgenin ayrı hatları var: 0533 395 01 39 ve sabit 0212 884 39 00.",
    paragraflar: [
      "Yazlığa geldiğiniz gün suyunuz hazır olsun: gelişinizden önce WhatsApp'tan yazın, varış gününüze göre teslimatı ayarlayalım. Site içindeki villalar ve apartmanlar için site adı ve blok bilgisini eklemeniz yeterli.",
      "Kumburgaz'daki kafe, restoran ve iş yerlerine de bardak su ve pet su kolisi ile düzenli teslimat yapıyoruz.",
    ],
  },
];

export const SSS_GENEL = [
  ["Su siparişi nasıl veririm?", "Üç yolu var: Celaliye ve Kamiloba için 0542 787 08 48'i, Kumburgaz ve Küme Evler için 0533 395 01 39'u arayın, WhatsApp'tan yazın ya da sitedeki sipariş formunu doldurun. Form, siparişinizi hazır bir WhatsApp mesajına dönüştürür; tek dokunuşla gönderirsiniz."],
  ["Siparişim ne zaman gelir?", "Siparişinizi en kısa sürede kapınıza getiriyoruz. Belirli bir saat istiyorsanız siparişte belirtin, ona göre planlayalım."],
  ["Hangi bölgelere teslimat yapıyorsunuz?", "Büyükçekmece'de Celaliye, Kamiloba ve Kumburgaz başta olmak üzere çevre mahallelere teslimat yapıyoruz. Mahalleniz listede yoksa arayın, hemen söyleyelim."],
  ["Hangi marka su getiriyorsunuz?", "19 L damacanada Çatalca Kalfaköy kaynaklı Mayadağ Doğal Kaynak Suyu getiriyoruz. Bardak ve pet suyun güncel markası için yazabilirsiniz."],
  ["Tüp gaz da getiriyor musunuz?", "Evet. Milangaz, Likitgaz ve Ergaz tüp gazı, dilerseniz su siparişinizle birlikte aynı teslimatta getiriyoruz."],
  ["Her hafta düzenli teslimat yapıyor musunuz?", "Evet. Ev ve iş yerleri için haftalık ya da iki haftada bir düzenli teslimat planlıyoruz; her seferinde yeniden sipariş vermenize gerek kalmıyor."],
  ["Kat ve asansör bilgisini yazmalı mıyım?", "Evet, yazmanız teslimatı hızlandırır. Site içindeyseniz blok adını, müstakil evdeyseniz tarif için yakındaki bir noktayı eklemeniz yeterli."],
];

export const SSS_EK = [
  ["Büyükçekmece'de size en yakın damacana su bayisi neresi?", "Bayimiz Celaliye, Uludere Sk. No:6A/2 adresinde. Buradan Celaliye, Kamiloba, Kumburgaz ve Büyükçekmece'nin çevre mahallelerine her gün servis çıkıyor; gelip almanıza gerek kalmadan kapınıza getiriyoruz."],
  ["Kaynak suyu ile doğal mineralli su arasındaki fark nedir?", "Türkiye'de doğal kaynak suyu ile doğal mineralli su ayrı yönetmeliklerle tanımlanan iki farklı su sınıfıdır. Mayadağ, etiketinde belirtildiği gibi bir doğal kaynak suyudur. Her iki su da doğal olarak mineral içerir; suyun mineral değerleri etiketinde yazar."],
  ["Kaliteli bir damacana su nasıl anlaşılır?", "Etikette kaynağın adı, üretici işletme bilgisi ve izin numarası yazmalı; kapak mühürlü ve sağlam olmalı; damacana temiz, çatlaksız ve güneşte bekletilmemiş olmalı; su berrak ve kokusuz olmalı. Mayadağ damacanalarımızı güneş görmeyen, temiz bir depoda saklıyoruz."],
  ["Toptan su satışı yapıyor musunuz?", "Evet. Tek damacanadan koli koli bardak ve pet suya kadar perakende ve toptan satış yapıyoruz. İşletmeler için ayrıntılar Toptan Su Tedarikçisi sayfamızda."],
  ["Damacanayı nasıl saklamalıyım?", "Doğrudan güneş almayan, serin ve kokusuz bir yerde saklayın. Deterjan, yakıt gibi kokulu ürünlerin yanında bekletmeyin; açılmış damacanayı kısa sürede tüketin."],
  ["Pompa da satıyor musunuz?", "Evet. Manuel ve şarjlı damacana pompalarını su siparişinizle birlikte getiriyoruz."],
  ["İşyerime fatura keserek teslimat yapar mısınız?", "Kurumsal siparişlerde fatura ve ödeme detaylarını sipariş sırasında telefonda ya da WhatsApp'ta birlikte netleştiriyoruz."],
  ["Bayiden gelip kendim alabilir miyim?", "Evet. Bayimiz Celaliye, Uludere Sk. No:6A/2 adresinde. Gelmeden önce aramanızı öneririz."],
];

export const YORUMLAR = [
  ["Mustafa I.", "Hızlı servis doğal su müşteri memnuniyet"],
  ["Vedat A.", "Güler yüz ve hızlı hizmet teşekkürü ederiz"],
  ["Mesut K.", "Tereddüt etmeden güvenebileceğiniz doğal kaynak suyu"],
];
